spring.application.name=AlAngulo

spring.datasource.url=jdbc:postgresql://localhost:5432/alangulodb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Esto crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update

# Dialecto para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- CONFIGURACION GOOGLE OAUTH2 ---
spring.security.oauth2.client.registration.google.client-id=641207688797-7nt3132gte5c16e6encpi6o432c3uird.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

weather.api.key=${WEATHER_API_KEY}
weather.api.url=https://api.openweathermap.org/data/2.5/weather

# CONFIGURACIÓN DE EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nicolasferreyramdp@gmail.com
spring.mail.password= ${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# MAIL ADMINS
app.security.admins = nicolasferreyramdp@gmail.com